#!/bin/sh
#
# Generated by /opt/zephyr/watcher

git show HEAD:entrypoint.sh
status=$?
if [ $status -eq 0 ]; then
    echo "(1.) entrypoint.sh found, running deployment"

    echo `pwd`
    
    # systemd-template-unit.service.hbs
    # echo "(2.) entrypoint.sh found, running deployment"
else
    echo "No entrypoint.sh, not running dynamic deploy"
fi
