#!/bin/sh

# Created in the /opt/zephyr/watcher codebase.
# This is run when trying to SSH into the git user
# This file should be symlinked to the git user's home directory at
# /home/git/git-shell-commands/no-interactive-login

printf '%s\n' "Hi $USER! You've successfully authenticated, but I do not"
printf '%s\n' "provide interactive shell access."
exit 128